Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.box_check_update = false
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provision "file", source: "./public/image.txt", destination: "/home/vagrant/"
  config.vm.host_name = "host-sf-practice"
  config.vm.provider "virtualbox" do |vb|
#     vb.gui = true
     vb.memory = "1024"
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get -y install build-essential zlib1g-dev libpq-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev wget libbz2-dev python3-dev python3-pip
     sudo pip3 install psycopg2
     sudo pip3 install django
   SHELL
end
